import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { motion } from "motion/react";

const FAQ_ITEMS = [
  {
    q: "Is a will generated by Will Maker AI legally valid?",
    a: "Documents generated by Will Maker AI are structured according to your jurisdiction's legal standards. However, to be fully valid, most jurisdictions require the will to be signed in front of witnesses and, in some cases, notarized. We guide you through these requirements — but this platform does not replace licensed legal advice.",
  },
  {
    q: "How does the AI generate my will?",
    a: "After you complete our step-by-step form with your personal details, beneficiaries, assets, and preferences, our AI analyzes your inputs and generates a comprehensive, personalized legal document. The process typically takes under 10 minutes.",
  },
  {
    q: "Can I update or edit my will after it's created?",
    a: "Absolutely. Life circumstances change, and your documents should reflect that. You can return to your dashboard at any time to edit your will, add new beneficiaries, update asset information, or change your executor designation.",
  },
  {
    q: "Is my personal and financial data secure?",
    a: "Security is our top priority. All data is encrypted in transit and at rest using enterprise-grade AES-256 encryption. We are built on the Internet Computer, which provides additional on-chain security guarantees. We never sell or share your data with third parties.",
  },
  {
    q: "What is the difference between a will and a power of attorney?",
    a: "A Last Will & Testament takes effect after your death and specifies how your assets should be distributed. A Power of Attorney is effective during your lifetime and authorizes someone to make financial or legal decisions on your behalf if you become unable to do so.",
  },
  {
    q: "Do I need to print and sign the documents?",
    a: "Yes — for the will to be legally enforceable, you must print it, sign it in front of the required number of witnesses (usually two), and in some states have it notarized. Our platform provides clear guidance on these steps based on your jurisdiction.",
  },
  {
    q: "Can I create multiple types of documents in one account?",
    a: "Yes. Free accounts can create one Last Will & Testament. Premium accounts have unlimited access to all document types including Power of Attorney, Healthcare Directives, and more. All documents are stored securely in your dashboard.",
  },
];

export function FAQ() {
  return (
    <section
      id="faq"
      className="py-20 lg:py-28 bg-background"
      data-ocid="faq.section"
    >
      <div className="mx-auto max-w-3xl px-4 sm:px-6">
        {/* Section header */}
        <motion.div
          className="text-center mb-12"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
        >
          <p className="text-sm font-semibold text-primary uppercase tracking-widest mb-3">
            FAQ
          </p>
          <h2 className="font-display font-bold text-3xl sm:text-4xl text-foreground">
            Frequently asked questions
          </h2>
          <p className="mt-4 text-base text-muted-foreground">
            Everything you need to know before getting started.
          </p>
        </motion.div>

        {/* Accordion */}
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5, delay: 0.1 }}
        >
          <Accordion type="single" collapsible className="w-full space-y-2">
            {FAQ_ITEMS.map((item, i) => (
              <AccordionItem
                key={item.q}
                value={`item-${i}`}
                className="glass border border-border/50 rounded-xl px-5 overflow-hidden data-[state=open]:border-primary/30"
                data-ocid={`faq.item.${i + 1}`}
              >
                <AccordionTrigger className="text-sm font-semibold text-foreground hover:no-underline py-4 text-left">
                  {item.q}
                </AccordionTrigger>
                <AccordionContent className="text-sm text-muted-foreground leading-relaxed pb-4">
                  {item.a}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </motion.div>
      </div>
    </section>
  );
}
