/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const PlatformStats = IDL.Record({
  'usersThisMonth' : IDL.Nat,
  'documentsThisMonth' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalDocuments' : IDL.Nat,
});
export const UserSummary = IDL.Record({
  'userId' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'documentCount' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DocumentStatus = IDL.Variant({
  'final' : IDL.Null,
  'draft' : IDL.Null,
});
export const DocumentType = IDL.Variant({
  'healthcareDirective' : IDL.Null,
  'powerOfAttorney' : IDL.Null,
  'lastWill' : IDL.Null,
});
export const PersonalDetails = IDL.Record({
  'country' : IDL.Text,
  'dateOfBirth' : IDL.Text,
  'city' : IDL.Text,
  'fullName' : IDL.Text,
  'state' : IDL.Text,
  'address' : IDL.Text,
  'maritalStatus' : IDL.Text,
});
export const Beneficiary = IDL.Record({
  'contact' : IDL.Text,
  'relationship' : IDL.Text,
  'name' : IDL.Text,
  'share' : IDL.Text,
});
export const Asset = IDL.Record({
  'beneficiaryName' : IDL.Text,
  'description' : IDL.Text,
  'estimatedValue' : IDL.Text,
  'assetType' : IDL.Text,
});
export const ExecutorInfo = IDL.Record({
  'guardianContact' : IDL.Text,
  'guardianRelationship' : IDL.Text,
  'executorRelationship' : IDL.Text,
  'executorContact' : IDL.Text,
  'guardianName' : IDL.Text,
  'executorName' : IDL.Text,
});
export const HealthcarePreferences = IDL.Record({
  'organDonation' : IDL.Text,
  'proxyContact' : IDL.Text,
  'healthcareProxy' : IDL.Text,
  'additionalWishes' : IDL.Text,
  'lifeSupport' : IDL.Text,
});
export const FormData = IDL.Record({
  'step1' : IDL.Opt(PersonalDetails),
  'step2' : IDL.Opt(IDL.Vec(Beneficiary)),
  'step3' : IDL.Opt(IDL.Vec(Asset)),
  'step4' : IDL.Opt(ExecutorInfo),
  'step5' : IDL.Opt(HealthcarePreferences),
});
export const CreateDocumentRequest = IDL.Record({
  'status' : DocumentStatus,
  'title' : IDL.Text,
  'documentType' : DocumentType,
  'formData' : FormData,
});
export const Document = IDL.Record({
  'id' : IDL.Text,
  'status' : DocumentStatus,
  'title' : IDL.Text,
  'documentType' : DocumentType,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'shareToken' : IDL.Opt(IDL.Text),
  'formData' : FormData,
  'updatedAt' : IDL.Int,
  'generatedContent' : IDL.Opt(IDL.Text),
});
export const DocumentId = IDL.Text;
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const ShareToken = IDL.Text;
export const UpdateDocumentRequest = IDL.Record({
  'status' : IDL.Opt(DocumentStatus),
  'title' : IDL.Opt(IDL.Text),
  'formData' : IDL.Opt(FormData),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'adminGetPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
  'adminListUsers' : IDL.Func([], [IDL.Vec(UserSummary)], ['query']),
  'adminSetOpenAIApiKey' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createDocument' : IDL.Func([CreateDocumentRequest], [Document], []),
  'deleteDocument' : IDL.Func([DocumentId], [IDL.Bool], []),
  'generateShareLink' : IDL.Func([DocumentId], [IDL.Text], []),
  'generateWillDocument' : IDL.Func([DocumentId], [IDL.Text], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDocument' : IDL.Func([DocumentId], [IDL.Opt(Document)], ['query']),
  'getDocumentByShareToken' : IDL.Func(
      [ShareToken],
      [IDL.Opt(Document)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isOpenAIConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listMyDocuments' : IDL.Func([], [IDL.Vec(Document)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateDocument' : IDL.Func(
      [DocumentId, UpdateDocumentRequest],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const PlatformStats = IDL.Record({
    'usersThisMonth' : IDL.Nat,
    'documentsThisMonth' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalDocuments' : IDL.Nat,
  });
  const UserSummary = IDL.Record({
    'userId' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'documentCount' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DocumentStatus = IDL.Variant({
    'final' : IDL.Null,
    'draft' : IDL.Null,
  });
  const DocumentType = IDL.Variant({
    'healthcareDirective' : IDL.Null,
    'powerOfAttorney' : IDL.Null,
    'lastWill' : IDL.Null,
  });
  const PersonalDetails = IDL.Record({
    'country' : IDL.Text,
    'dateOfBirth' : IDL.Text,
    'city' : IDL.Text,
    'fullName' : IDL.Text,
    'state' : IDL.Text,
    'address' : IDL.Text,
    'maritalStatus' : IDL.Text,
  });
  const Beneficiary = IDL.Record({
    'contact' : IDL.Text,
    'relationship' : IDL.Text,
    'name' : IDL.Text,
    'share' : IDL.Text,
  });
  const Asset = IDL.Record({
    'beneficiaryName' : IDL.Text,
    'description' : IDL.Text,
    'estimatedValue' : IDL.Text,
    'assetType' : IDL.Text,
  });
  const ExecutorInfo = IDL.Record({
    'guardianContact' : IDL.Text,
    'guardianRelationship' : IDL.Text,
    'executorRelationship' : IDL.Text,
    'executorContact' : IDL.Text,
    'guardianName' : IDL.Text,
    'executorName' : IDL.Text,
  });
  const HealthcarePreferences = IDL.Record({
    'organDonation' : IDL.Text,
    'proxyContact' : IDL.Text,
    'healthcareProxy' : IDL.Text,
    'additionalWishes' : IDL.Text,
    'lifeSupport' : IDL.Text,
  });
  const FormData = IDL.Record({
    'step1' : IDL.Opt(PersonalDetails),
    'step2' : IDL.Opt(IDL.Vec(Beneficiary)),
    'step3' : IDL.Opt(IDL.Vec(Asset)),
    'step4' : IDL.Opt(ExecutorInfo),
    'step5' : IDL.Opt(HealthcarePreferences),
  });
  const CreateDocumentRequest = IDL.Record({
    'status' : DocumentStatus,
    'title' : IDL.Text,
    'documentType' : DocumentType,
    'formData' : FormData,
  });
  const Document = IDL.Record({
    'id' : IDL.Text,
    'status' : DocumentStatus,
    'title' : IDL.Text,
    'documentType' : DocumentType,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'shareToken' : IDL.Opt(IDL.Text),
    'formData' : FormData,
    'updatedAt' : IDL.Int,
    'generatedContent' : IDL.Opt(IDL.Text),
  });
  const DocumentId = IDL.Text;
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ShareToken = IDL.Text;
  const UpdateDocumentRequest = IDL.Record({
    'status' : IDL.Opt(DocumentStatus),
    'title' : IDL.Opt(IDL.Text),
    'formData' : IDL.Opt(FormData),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'adminGetPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
    'adminListUsers' : IDL.Func([], [IDL.Vec(UserSummary)], ['query']),
    'adminSetOpenAIApiKey' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createDocument' : IDL.Func([CreateDocumentRequest], [Document], []),
    'deleteDocument' : IDL.Func([DocumentId], [IDL.Bool], []),
    'generateShareLink' : IDL.Func([DocumentId], [IDL.Text], []),
    'generateWillDocument' : IDL.Func([DocumentId], [IDL.Text], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDocument' : IDL.Func([DocumentId], [IDL.Opt(Document)], ['query']),
    'getDocumentByShareToken' : IDL.Func(
        [ShareToken],
        [IDL.Opt(Document)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isOpenAIConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listMyDocuments' : IDL.Func([], [IDL.Vec(Document)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateDocument' : IDL.Func(
        [DocumentId, UpdateDocumentRequest],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };