/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Asset {
  'beneficiaryName' : string,
  'description' : string,
  'estimatedValue' : string,
  'assetType' : string,
}
export interface Beneficiary {
  'contact' : string,
  'relationship' : string,
  'name' : string,
  'share' : string,
}
export interface CreateDocumentRequest {
  'status' : DocumentStatus,
  'title' : string,
  'documentType' : DocumentType,
  'formData' : FormData,
}
export interface Document {
  'id' : string,
  'status' : DocumentStatus,
  'title' : string,
  'documentType' : DocumentType,
  'userId' : Principal,
  'createdAt' : bigint,
  'shareToken' : [] | [string],
  'formData' : FormData,
  'updatedAt' : bigint,
  'generatedContent' : [] | [string],
}
export type DocumentId = string;
export type DocumentStatus = { 'final' : null } |
  { 'draft' : null };
export type DocumentType = { 'healthcareDirective' : null } |
  { 'powerOfAttorney' : null } |
  { 'lastWill' : null };
export interface ExecutorInfo {
  'guardianContact' : string,
  'guardianRelationship' : string,
  'executorRelationship' : string,
  'executorContact' : string,
  'guardianName' : string,
  'executorName' : string,
}
export interface FormData {
  'step1' : [] | [PersonalDetails],
  'step2' : [] | [Array<Beneficiary>],
  'step3' : [] | [Array<Asset>],
  'step4' : [] | [ExecutorInfo],
  'step5' : [] | [HealthcarePreferences],
}
export interface HealthcarePreferences {
  'organDonation' : string,
  'proxyContact' : string,
  'healthcareProxy' : string,
  'additionalWishes' : string,
  'lifeSupport' : string,
}
export interface PersonalDetails {
  'country' : string,
  'dateOfBirth' : string,
  'city' : string,
  'fullName' : string,
  'state' : string,
  'address' : string,
  'maritalStatus' : string,
}
export interface PlatformStats {
  'usersThisMonth' : bigint,
  'documentsThisMonth' : bigint,
  'totalUsers' : bigint,
  'totalDocuments' : bigint,
}
export type ShareToken = string;
export interface UpdateDocumentRequest {
  'status' : [] | [DocumentStatus],
  'title' : [] | [string],
  'formData' : [] | [FormData],
}
export interface UserProfile {
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSummary {
  'userId' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'documentCount' : bigint,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'adminGetPlatformStats' : ActorMethod<[], PlatformStats>,
  'adminListUsers' : ActorMethod<[], Array<UserSummary>>,
  'adminSetOpenAIApiKey' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createDocument' : ActorMethod<[CreateDocumentRequest], Document>,
  'deleteDocument' : ActorMethod<[DocumentId], boolean>,
  'generateShareLink' : ActorMethod<[DocumentId], string>,
  'generateWillDocument' : ActorMethod<[DocumentId], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDocument' : ActorMethod<[DocumentId], [] | [Document]>,
  'getDocumentByShareToken' : ActorMethod<[ShareToken], [] | [Document]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isOpenAIConfigured' : ActorMethod<[], boolean>,
  'listMyDocuments' : ActorMethod<[], Array<Document>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateDocument' : ActorMethod<[DocumentId, UpdateDocumentRequest], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];