/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface HealthcarePreferences {
    organDonation: string;
    proxyContact: string;
    healthcareProxy: string;
    additionalWishes: string;
    lifeSupport: string;
}
export interface Beneficiary {
    contact: string;
    relationship: string;
    name: string;
    share: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface PersonalDetails {
    country: string;
    dateOfBirth: string;
    city: string;
    fullName: string;
    state: string;
    address: string;
    maritalStatus: string;
}
export interface Document {
    id: string;
    status: DocumentStatus;
    title: string;
    documentType: DocumentType;
    userId: Principal;
    createdAt: bigint;
    shareToken?: string;
    formData: FormData;
    updatedAt: bigint;
    generatedContent?: string;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UpdateDocumentRequest {
    status?: DocumentStatus;
    title?: string;
    formData?: FormData;
}
export interface ExecutorInfo {
    guardianContact: string;
    guardianRelationship: string;
    executorRelationship: string;
    executorContact: string;
    guardianName: string;
    executorName: string;
}
export interface UserSummary {
    userId: Principal;
    name: string;
    createdAt: bigint;
    email: string;
    documentCount: bigint;
}
export type DocumentId = string;
export interface FormData {
    step1?: PersonalDetails;
    step2?: Array<Beneficiary>;
    step3?: Array<Asset>;
    step4?: ExecutorInfo;
    step5?: HealthcarePreferences;
}
export interface Asset {
    beneficiaryName: string;
    description: string;
    estimatedValue: string;
    assetType: string;
}
export interface CreateDocumentRequest {
    status: DocumentStatus;
    title: string;
    documentType: DocumentType;
    formData: FormData;
}
export interface PlatformStats {
    usersThisMonth: bigint;
    documentsThisMonth: bigint;
    totalUsers: bigint;
    totalDocuments: bigint;
}
export interface UserProfile {
    name: string;
    createdAt: bigint;
    email: string;
    phone: string;
}
export type ShareToken = string;
export enum DocumentStatus {
    final_ = "final",
    draft = "draft"
}
export enum DocumentType {
    healthcareDirective = "healthcareDirective",
    powerOfAttorney = "powerOfAttorney",
    lastWill = "lastWill"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    adminGetPlatformStats(): Promise<PlatformStats>;
    adminListUsers(): Promise<Array<UserSummary>>;
    adminSetOpenAIApiKey(key: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createDocument(req: CreateDocumentRequest): Promise<Document>;
    deleteDocument(docId: DocumentId): Promise<boolean>;
    generateShareLink(docId: DocumentId): Promise<string>;
    generateWillDocument(docId: DocumentId): Promise<string>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDocument(docId: DocumentId): Promise<Document | null>;
    getDocumentByShareToken(token: ShareToken): Promise<Document | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isOpenAIConfigured(): Promise<boolean>;
    listMyDocuments(): Promise<Array<Document>>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateDocument(docId: DocumentId, req: UpdateDocumentRequest): Promise<boolean>;
}
import type { Asset as _Asset, Beneficiary as _Beneficiary, CreateDocumentRequest as _CreateDocumentRequest, Document as _Document, DocumentStatus as _DocumentStatus, DocumentType as _DocumentType, ExecutorInfo as _ExecutorInfo, FormData as _FormData, HealthcarePreferences as _HealthcarePreferences, PersonalDetails as _PersonalDetails, UpdateDocumentRequest as _UpdateDocumentRequest, UserProfile as _UserProfile, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async adminGetPlatformStats(): Promise<PlatformStats> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetPlatformStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetPlatformStats();
            return result;
        }
    }
    async adminListUsers(): Promise<Array<UserSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListUsers();
            return result;
        }
    }
    async adminSetOpenAIApiKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSetOpenAIApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSetOpenAIApiKey(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createDocument(arg0: CreateDocumentRequest): Promise<Document> {
        if (this.processError) {
            try {
                const result = await this.actor.createDocument(to_candid_CreateDocumentRequest_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Document_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDocument(to_candid_CreateDocumentRequest_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Document_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteDocument(arg0: DocumentId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDocument(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDocument(arg0);
            return result;
        }
    }
    async generateShareLink(arg0: DocumentId): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateShareLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateShareLink(arg0);
            return result;
        }
    }
    async generateWillDocument(arg0: DocumentId): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateWillDocument(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateWillDocument(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDocument(arg0: DocumentId): Promise<Document | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocument(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocument(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDocumentByShareToken(arg0: ShareToken): Promise<Document | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocumentByShareToken(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocumentByShareToken(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isOpenAIConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isOpenAIConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isOpenAIConfigured();
            return result;
        }
    }
    async listMyDocuments(): Promise<Array<Document>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyDocuments();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyDocuments();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateDocument(arg0: DocumentId, arg1: UpdateDocumentRequest): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDocument(arg0, to_candid_UpdateDocumentRequest_n37(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDocument(arg0, to_candid_UpdateDocumentRequest_n37(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_DocumentStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DocumentStatus): DocumentStatus {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_DocumentType_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DocumentType): DocumentType {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Document_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Document): Document {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_FormData_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FormData): FormData {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PersonalDetails]): PersonalDetails | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_Beneficiary>]): Array<Beneficiary> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_Asset>]): Array<Asset> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExecutorInfo]): ExecutorInfo | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_HealthcarePreferences]): HealthcarePreferences | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Document]): Document | null {
    return value.length === 0 ? null : from_candid_Document_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _DocumentStatus;
    title: string;
    documentType: _DocumentType;
    userId: Principal;
    createdAt: bigint;
    shareToken: [] | [string];
    formData: _FormData;
    updatedAt: bigint;
    generatedContent: [] | [string];
}): {
    id: string;
    status: DocumentStatus;
    title: string;
    documentType: DocumentType;
    userId: Principal;
    createdAt: bigint;
    shareToken?: string;
    formData: FormData;
    updatedAt: bigint;
    generatedContent?: string;
} {
    return {
        id: value.id,
        status: from_candid_DocumentStatus_n20(_uploadFile, _downloadFile, value.status),
        title: value.title,
        documentType: from_candid_DocumentType_n22(_uploadFile, _downloadFile, value.documentType),
        userId: value.userId,
        createdAt: value.createdAt,
        shareToken: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.shareToken)),
        formData: from_candid_FormData_n25(_uploadFile, _downloadFile, value.formData),
        updatedAt: value.updatedAt,
        generatedContent: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.generatedContent))
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    step1: [] | [_PersonalDetails];
    step2: [] | [Array<_Beneficiary>];
    step3: [] | [Array<_Asset>];
    step4: [] | [_ExecutorInfo];
    step5: [] | [_HealthcarePreferences];
}): {
    step1?: PersonalDetails;
    step2?: Array<Beneficiary>;
    step3?: Array<Asset>;
    step4?: ExecutorInfo;
    step5?: HealthcarePreferences;
} {
    return {
        step1: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.step1)),
        step2: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.step2)),
        step3: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.step3)),
        step4: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.step4)),
        step5: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.step5))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    final: null;
} | {
    draft: null;
}): DocumentStatus {
    return "final" in value ? DocumentStatus.final : "draft" in value ? DocumentStatus.draft : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    healthcareDirective: null;
} | {
    powerOfAttorney: null;
} | {
    lastWill: null;
}): DocumentType {
    return "healthcareDirective" in value ? DocumentType.healthcareDirective : "powerOfAttorney" in value ? DocumentType.powerOfAttorney : "lastWill" in value ? DocumentType.lastWill : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Document>): Array<Document> {
    return value.map((x)=>from_candid_Document_n18(_uploadFile, _downloadFile, x));
}
function to_candid_CreateDocumentRequest_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateDocumentRequest): _CreateDocumentRequest {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_DocumentStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocumentStatus): _DocumentStatus {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_DocumentType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocumentType): _DocumentType {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_FormData_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FormData): _FormData {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateDocumentRequest_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateDocumentRequest): _UpdateDocumentRequest {
    return to_candid_record_n38(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: DocumentStatus;
    title: string;
    documentType: DocumentType;
    formData: FormData;
}): {
    status: _DocumentStatus;
    title: string;
    documentType: _DocumentType;
    formData: _FormData;
} {
    return {
        status: to_candid_DocumentStatus_n12(_uploadFile, _downloadFile, value.status),
        title: value.title,
        documentType: to_candid_DocumentType_n14(_uploadFile, _downloadFile, value.documentType),
        formData: to_candid_FormData_n16(_uploadFile, _downloadFile, value.formData)
    };
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    step1?: PersonalDetails;
    step2?: Array<Beneficiary>;
    step3?: Array<Asset>;
    step4?: ExecutorInfo;
    step5?: HealthcarePreferences;
}): {
    step1: [] | [_PersonalDetails];
    step2: [] | [Array<_Beneficiary>];
    step3: [] | [Array<_Asset>];
    step4: [] | [_ExecutorInfo];
    step5: [] | [_HealthcarePreferences];
} {
    return {
        step1: value.step1 ? candid_some(value.step1) : candid_none(),
        step2: value.step2 ? candid_some(value.step2) : candid_none(),
        step3: value.step3 ? candid_some(value.step3) : candid_none(),
        step4: value.step4 ? candid_some(value.step4) : candid_none(),
        step5: value.step5 ? candid_some(value.step5) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: DocumentStatus;
    title?: string;
    formData?: FormData;
}): {
    status: [] | [_DocumentStatus];
    title: [] | [string];
    formData: [] | [_FormData];
} {
    return {
        status: value.status ? candid_some(to_candid_DocumentStatus_n12(_uploadFile, _downloadFile, value.status)) : candid_none(),
        title: value.title ? candid_some(value.title) : candid_none(),
        formData: value.formData ? candid_some(to_candid_FormData_n16(_uploadFile, _downloadFile, value.formData)) : candid_none()
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocumentStatus): {
    final: null;
} | {
    draft: null;
} {
    return value == DocumentStatus.final ? {
        final_: null
    } : value == DocumentStatus.draft ? {
        draft: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocumentType): {
    healthcareDirective: null;
} | {
    powerOfAttorney: null;
} | {
    lastWill: null;
} {
    return value == DocumentType.healthcareDirective ? {
        healthcareDirective: null
    } : value == DocumentType.powerOfAttorney ? {
        powerOfAttorney: null
    } : value == DocumentType.lastWill ? {
        lastWill: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
