/* prettier-ignore-start */
/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute, createRootRoute } from "@tanstack/react-router";

import { Route as rootRoute } from "./routes/__root";

import { Route as AdminImport } from "./routes/admin";
import { Route as DashboardImport } from "./routes/dashboard";
import { Route as DocumentIdImport } from "./routes/document.$id";
import { Route as GeneratorImport } from "./routes/generator";
import { Route as GeneratorIdImport } from "./routes/generator.$id";
import { Route as IndexImport } from "./routes/index";
import { Route as ShareTokenImport } from "./routes/share.$token";
import { Route as SignInImport } from "./routes/signin";
import { Route as SignUpImport } from "./routes/signup";

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as never);

const SignInRoute = SignInImport.update({
  id: "/signin",
  path: "/signin",
  getParentRoute: () => rootRoute,
} as never);

const SignUpRoute = SignUpImport.update({
  id: "/signup",
  path: "/signup",
  getParentRoute: () => rootRoute,
} as never);

const DashboardRoute = DashboardImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRoute,
} as never);

const GeneratorRoute = GeneratorImport.update({
  id: "/generator",
  path: "/generator",
  getParentRoute: () => rootRoute,
} as never);

const GeneratorIdRoute = GeneratorIdImport.update({
  id: "/generator/$id",
  path: "/generator/$id",
  getParentRoute: () => rootRoute,
} as never);

const DocumentIdRoute = DocumentIdImport.update({
  id: "/document/$id",
  path: "/document/$id",
  getParentRoute: () => rootRoute,
} as never);

const AdminRoute = AdminImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => rootRoute,
} as never);

const ShareTokenRoute = ShareTokenImport.update({
  id: "/share/$token",
  path: "/share/$token",
  getParentRoute: () => rootRoute,
} as never);

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/signin": {
      id: "/signin";
      path: "/signin";
      fullPath: "/signin";
      preLoaderRoute: typeof SignInImport;
      parentRoute: typeof rootRoute;
    };
    "/signup": {
      id: "/signup";
      path: "/signup";
      fullPath: "/signup";
      preLoaderRoute: typeof SignUpImport;
      parentRoute: typeof rootRoute;
    };
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardImport;
      parentRoute: typeof rootRoute;
    };
    "/generator": {
      id: "/generator";
      path: "/generator";
      fullPath: "/generator";
      preLoaderRoute: typeof GeneratorImport;
      parentRoute: typeof rootRoute;
    };
    "/generator/$id": {
      id: "/generator/$id";
      path: "/generator/$id";
      fullPath: "/generator/$id";
      preLoaderRoute: typeof GeneratorIdImport;
      parentRoute: typeof rootRoute;
    };
    "/document/$id": {
      id: "/document/$id";
      path: "/document/$id";
      fullPath: "/document/$id";
      preLoaderRoute: typeof DocumentIdImport;
      parentRoute: typeof rootRoute;
    };
    "/admin": {
      id: "/admin";
      path: "/admin";
      fullPath: "/admin";
      preLoaderRoute: typeof AdminImport;
      parentRoute: typeof rootRoute;
    };
    "/share/$token": {
      id: "/share/$token";
      path: "/share/$token";
      fullPath: "/share/$token";
      preLoaderRoute: typeof ShareTokenImport;
      parentRoute: typeof rootRoute;
    };
  }
}

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  SignInRoute,
  SignUpRoute,
  DashboardRoute,
  GeneratorRoute,
  GeneratorIdRoute,
  DocumentIdRoute,
  AdminRoute,
  ShareTokenRoute,
]);

export type FileRouteTypes = {
  fileRoutesByPath: {
    "/": typeof IndexRoute;
    "/signin": typeof SignInRoute;
    "/signup": typeof SignUpRoute;
    "/dashboard": typeof DashboardRoute;
    "/generator": typeof GeneratorRoute;
    "/generator/$id": typeof GeneratorIdRoute;
    "/document/$id": typeof DocumentIdRoute;
    "/admin": typeof AdminRoute;
    "/share/$token": typeof ShareTokenRoute;
  };
  fullPaths:
    | "/"
    | "/signin"
    | "/signup"
    | "/dashboard"
    | "/generator"
    | "/generator/$id"
    | "/document/$id"
    | "/admin"
    | "/share/$token";
  allParams: { id: string } | { token: string };
  routeIds:
    | "/"
    | "/signin"
    | "/signup"
    | "/dashboard"
    | "/generator"
    | "/generator/$id"
    | "/document/$id"
    | "/admin"
    | "/share/$token";
};
/* prettier-ignore-end */
